### ISSUE TITLE
Project development seems to have stalled 

### ISSUE THREAD

**Issue by johnny88** [janez89/mongoose-materialized#28]
There hasn't been an update with this package for a couple years and there are still a few bugs in it that need to be worked out.

We've created a forked project where we can continue development. So if you have any issues with this lib and they haven't/aren't being addressed you can head over to [this github](https://github.com/BobbyDigitalStudios/materialized-mongoose) or [this npm module](https://www.npmjs.com/package/materialized-mongoose).

So far we have implemented the following fixes:
- MongoDB 3.2 Limit / Skip not working (Thanks @joniba)
- Fix for very long paths (adds a text index, normal indexes fail)

If you have any questions or concerns you can reach us at: interactive@bobby.se

Thanks!

**Comment by janez89** [comment]
Thanks the information.
Now, I fixed this issue.

**Comment by johnny88** [comment]
The system works! Thanks so much. I'll close this ticket now.
